-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
/*
Eduardo Alvarado
CST-204-001
10/31/2025
Prof. Elble
Schema.sql
*/


 
-- TABLE: Admission_Class
CREATE TABLE IF NOT EXISTS PUBLIC."Admission_Class" (
	"ClassCode" CHARACTER VARYING(4) COLLATE PG_CATALOG."default" NOT NULL,
	"ClassDescription" CHARACTER VARYING(255) COLLATE PG_CATALOG."default" NOT NULL,
	"IsPermanentResidentClass" BOOLEAN NOT NULL,
	CONSTRAINT "Admission_Class_pkey" PRIMARY KEY ("ClassCode")
);

COMMENT ON TABLE PUBLIC."Admission_Class" IS 'Classes of Admission for nonimmigrant visas, immigrant visas, ARC (Alien Resident Card), Citizens';

-- TABLE: Country
CREATE TABLE IF NOT EXISTS PUBLIC."Country" (
	"CountryID" SMALLSERIAL NOT NULL,
	"CountryCode" CHARACTER(3) COLLATE PG_CATALOG."default" NOT NULL,
	"CountryName" CHARACTER VARYING(40) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT "Country_pkey" PRIMARY KEY ("CountryCode"),
	CONSTRAINT "Country_CountryID_key" UNIQUE ("CountryID")
);

COMMENT ON TABLE PUBLIC."Country" IS 'Country list to eventually be able to select on a join dropdown.';

-- TABLE: Passport (FIXED: Composite PK)
CREATE TABLE IF NOT EXISTS PUBLIC."Passport" (
	"PassportNumber" CHARACTER VARYING(9) COLLATE PG_CATALOG."default" NOT NULL,
	"CountryCode" CHARACTER(3) COLLATE PG_CATALOG."default" NOT NULL,
	"GivenName" CHARACTER VARYING(50) COLLATE PG_CATALOG."default" NOT NULL,
	"Surname" CHARACTER VARYING(50) COLLATE PG_CATALOG."default" NOT NULL,
	"IssueDate" DATE NOT NULL,
	"ExpDate" DATE NOT NULL,

	CONSTRAINT "Passport_pkey" PRIMARY KEY ("PassportNumber", "CountryCode")
);

COMMENT ON TABLE PUBLIC."Passport" IS 'Stores passport details; Primary key is composite to handle non-unique passport numbers globally.';

-- TABLE: Flight
CREATE TABLE IF NOT EXISTS PUBLIC."Flight" (
	"FlightID" SERIAL NOT NULL,
	"AirlineCode" CHARACTER VARYING(3) COLLATE PG_CATALOG."default" NOT NULL,
	"FlightNumber" CHARACTER VARYING(6) COLLATE PG_CATALOG."default" NOT NULL,
	"OriginAirportCode" CHARACTER VARYING(3) COLLATE PG_CATALOG."default" NOT NULL,
	"FlightDate" DATE NOT NULL,
	"CountryCode" CHARACTER(3) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT "Flight_pkey" PRIMARY KEY ("FlightID"),
	CONSTRAINT "Flight_Unique_Event" UNIQUE (
		"AirlineCode",
		"FlightNumber",
		"OriginAirportCode",
		"FlightDate"
	)
);

COMMENT ON TABLE PUBLIC."Flight" IS 'Stores details about incoming flights.';

-- TABLE: Person (FIXED: Added PassportCountryCode FK column)
CREATE TABLE IF NOT EXISTS PUBLIC."Person" (
	"PersonID" SERIAL NOT NULL,
	"GivenName" CHARACTER VARYING(50) COLLATE PG_CATALOG."default" NOT NULL,
	"Surname" CHARACTER VARYING(50) COLLATE PG_CATALOG."default" NOT NULL,
	"ANumber" CHARACTER VARYING(10) COLLATE PG_CATALOG."default",
	"DateOfBirth" DATE NOT NULL,
	"PassportNumber" CHARACTER VARYING(9) COLLATE PG_CATALOG."default" NOT NULL,
	"PassportCountryCode" CHARACTER(3) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT "Person_pkey" PRIMARY KEY ("PersonID"),
	CONSTRAINT "Person_Unique_Passport" UNIQUE ("PassportNumber", "PassportCountryCode")
);

COMMENT ON TABLE PUBLIC."Person" IS 'Stores biographic details for each individual. Links to the unique passport record via the composite key.';

-- TABLE: I_94
CREATE TABLE IF NOT EXISTS PUBLIC."I_94" (
	"RecordID" SERIAL NOT NULL,
	"PersonID" INTEGER NOT NULL,
	"FlightID" INTEGER NOT NULL,
	"ClassCode" CHARACTER VARYING(4) COLLATE PG_CATALOG."default" NOT NULL,
	"EntryDate" DATE NOT NULL,
	"Admitted" BOOLEAN NOT NULL,
	"ExitDate" DATE,
	"NotAdmittedReason" CHARACTER VARYING(255) COLLATE PG_CATALOG."default",
	CONSTRAINT "I_94_pkey" PRIMARY KEY ("RecordID")
);

COMMENT ON TABLE PUBLIC."I_94" IS 'The core arrival/departure record (I-94), linking a person and a flight to an admission class.';

-- TABLE: Person_Admission_Class
CREATE TABLE IF NOT EXISTS PUBLIC."Person_Admission_Class" (
	"PersonID" INTEGER NOT NULL,
	"ClassCode" CHARACTER VARYING(4) COLLATE PG_CATALOG."default" NOT NULL,
	"I94RecordID" INTEGER NOT NULL,
	"GrantDate" DATE NOT NULL,
	CONSTRAINT "Person_Admission_Class_pkey" PRIMARY KEY ("PersonID", "ClassCode", "I94RecordID")
);

COMMENT ON TABLE PUBLIC."Person_Admission_Class" IS 'Bridge table to track the history of admission classes granted to a person.';

-- ---------------------------------------------------
-- 3. FOREIGN KEY CONSTRAINTS
ALTER TABLE IF EXISTS PUBLIC."Passport"
ADD CONSTRAINT FK_PASSPORT_COUNTRY FOREIGN KEY ("CountryCode") REFERENCES PUBLIC."Country" ("CountryCode") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE RESTRICT;

-- Flight FK to Country (Flight originated from Country)
ALTER TABLE IF EXISTS PUBLIC."Flight"
ADD CONSTRAINT FK_FLIGHT_COUNTRY FOREIGN KEY ("CountryCode") REFERENCES PUBLIC."Country" ("CountryCode") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE RESTRICT;

-- Person FK to Passport (CORRECTED: Now referencing the composite key)
ALTER TABLE IF EXISTS PUBLIC."Person"
ADD CONSTRAINT FK_PERSON_PASSPORT FOREIGN KEY ("PassportNumber", "PassportCountryCode") REFERENCES PUBLIC."Passport" ("PassportNumber", "CountryCode") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE RESTRICT;

-- I_94 FKs
ALTER TABLE IF EXISTS PUBLIC."I_94"
ADD CONSTRAINT FK_I94_PERSON FOREIGN KEY ("PersonID") REFERENCES PUBLIC."Person" ("PersonID") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;

-- R8
ALTER TABLE IF EXISTS PUBLIC."I_94"
ADD CONSTRAINT FK_I94_FLIGHT FOREIGN KEY ("FlightID") REFERENCES PUBLIC."Flight" ("FlightID") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;

-- R9
ALTER TABLE IF EXISTS PUBLIC."I_94"
ADD CONSTRAINT FK_I94_ADMISSION_CLASS FOREIGN KEY ("ClassCode") REFERENCES PUBLIC."Admission_Class" ("ClassCode") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE RESTRICT;

-- Person_Admission_Class FKs
ALTER TABLE IF EXISTS PUBLIC."Person_Admission_Class"
ADD CONSTRAINT FK_PAC_PERSON FOREIGN KEY ("PersonID") REFERENCES PUBLIC."Person" ("PersonID") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS PUBLIC."Person_Admission_Class"
ADD CONSTRAINT FK_PAC_I94 FOREIGN KEY ("I94RecordID") REFERENCES PUBLIC."I_94" ("RecordID") MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;

-- R10
ALTER TABLE IF EXISTS PUBLIC."Person_Admission_Class"
ADD CONSTRAINT FK_PAC_ADMISSION_CLASS FOREIGN KEY ("ClassCode") REFERENCES PUBLIC."Admission_Class" ("ClassCode") MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;

COMMIT;